version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
      - celery
    command: ["poetry", "run", "uvicorn", "sample_paper.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    image: "redis:alpine"

    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/data/db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    command: ["poetry", "run", "celery", "-A", "sample_paper.task", "worker", "--loglevel=info"]

volumes:
  redis-data:
  mongo-data: